# Auto-generated by mk_wml.py
# Filebench fileserver-like foreground workload

define fileset name=fbset0,path=/nvme/media/gc_exp/20260527_155009_nodiscard_data/filebench/set_0,entries=184320,dirwidth=64,size=1m,prealloc=85

define process name=fbproc0,instances=1
{
  thread name=fbthr0,memsize=10m,instances=16
  {
    flowop createfile name=create0,filesetname=fbset0,fd=1
    flowop writewholefile name=write0,fd=1,iosize=1m
    flowop closefile name=close_create0,fd=1
    flowop openfile name=open_read0,filesetname=fbset0,fd=1
    flowop readwholefile name=read0,fd=1,iosize=1m
    flowop closefile name=close_read0,fd=1
    flowop openfile name=open_append0,filesetname=fbset0,fd=1
    flowop appendfilerand name=append0,fd=1,iosize=16k
    flowop closefile name=close_append0,fd=1
    flowop statfile name=stat0,filesetname=fbset0
    flowop deletefile name=delete0,filesetname=fbset0
  }
}

run 900
