#!/usr/bin/env python3
"""Generate a Filebench fileserver-like workload for the GC/discard experiment."""
from __future__ import annotations

import argparse
from pathlib import Path


def shell_quote_for_wml(path: str) -> str:
    return path.replace(' ', '\\ ')


def size_literal_from_kib(kib: int) -> str:
    if kib % 1024 == 0:
        return f"{kib // 1024}m"
    return f"{kib}k"


def split_threads(total: int, groups: int) -> list[int]:
    total = max(1, total)
    groups = max(1, groups)
    base = total // groups
    rem = total % groups
    return [max(1, base + (1 if i < rem else 0)) for i in range(groups)]


def generate(args: argparse.Namespace) -> str:
    fb_dir = shell_quote_for_wml(str(Path(args.fb_dir).resolve()))
    set_count = max(1, args.set_count)
    threads = split_threads(args.threads_total, set_count)
    mean_size = size_literal_from_kib(args.mean_file_kib)

    lines: list[str] = []
    lines.append("# Auto-generated by mk_wml.py")
    lines.append("# Filebench fileserver-like foreground workload")
    lines.append("")

    for i in range(set_count):
        path = f"{fb_dir}/set_{i}"
        lines.append(
            "define fileset "
            f"name=fbset{i},path={path},entries={args.entries_per_set},"
            f"dirwidth={args.dirwidth},size={mean_size},prealloc={args.prealloc}"
        )
    lines.append("")

    for i, nthreads in enumerate(threads):
        lines.append(f"define process name=fbproc{i},instances=1")
        lines.append("{")
        lines.append(f"  thread name=fbthr{i},memsize=10m,instances={nthreads}")
        lines.append("  {")
        lines.append(f"    flowop createfile name=create{i},filesetname=fbset{i},fd=1")
        lines.append(f"    flowop writewholefile name=write{i},fd=1,iosize={args.iosize}")
        lines.append(f"    flowop closefile name=close_create{i},fd=1")
        lines.append(f"    flowop openfile name=open_read{i},filesetname=fbset{i},fd=1")
        lines.append(f"    flowop readwholefile name=read{i},fd=1,iosize={args.iosize}")
        lines.append(f"    flowop closefile name=close_read{i},fd=1")
        lines.append(f"    flowop openfile name=open_append{i},filesetname=fbset{i},fd=1")
        lines.append(f"    flowop appendfilerand name=append{i},fd=1,iosize={args.append_size}")
        lines.append(f"    flowop closefile name=close_append{i},fd=1")
        lines.append(f"    flowop statfile name=stat{i},filesetname=fbset{i}")
        lines.append(f"    flowop deletefile name=delete{i},filesetname=fbset{i}")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    lines.append(f"run {args.runtime_sec}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument('--out-dir', required=True)
    p.add_argument('--fb-dir', required=True)
    p.add_argument('--set-count', type=int, required=True)
    p.add_argument('--entries-per-set', type=int, required=True)
    p.add_argument('--prealloc', type=int, required=True)
    p.add_argument('--dirwidth', type=int, required=True)
    p.add_argument('--mean-file-kib', type=int, required=True)
    p.add_argument('--runtime-sec', type=int, required=True)
    p.add_argument('--iosize', required=True)
    p.add_argument('--append-size', required=True)
    p.add_argument('--threads-total', type=int, required=True)
    args = p.parse_args()

    if args.prealloc < 0 or args.prealloc > 100:
        raise SystemExit('--prealloc must be 0..100')
    if args.entries_per_set < 1:
        raise SystemExit('--entries-per-set must be >= 1')
    if args.mean_file_kib < 1:
        raise SystemExit('--mean-file-kib must be >= 1')

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    Path(args.fb_dir).mkdir(parents=True, exist_ok=True)
    for i in range(max(1, args.set_count)):
        Path(args.fb_dir, f"set_{i}").mkdir(parents=True, exist_ok=True)

    (out_dir / 'run.f').write_text(generate(args), encoding='utf-8')
    (out_dir / 'run.f.meta').write_text(
        f"fb_dir={Path(args.fb_dir).resolve()}\n"
        f"set_count={args.set_count}\n"
        f"entries_per_set={args.entries_per_set}\n"
        f"prealloc={args.prealloc}\n"
        f"mean_file_kib={args.mean_file_kib}\n"
        f"runtime_sec={args.runtime_sec}\n"
        f"threads_total={args.threads_total}\n",
        encoding='utf-8',
    )


if __name__ == '__main__':
    main()

